name: CI/CD Pipeline

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ test, master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
    
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml

  unit-tests:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test' || (github.event_name == 'pull_request' && github.base_ref == 'test')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        pytest tests/ -v --cov=. --cov-report=html
    
    - name: Build Docker image
      run: |
        docker build -t zomato-flask-app:${{ github.sha }} .
    
    - name: Test Docker image
      run: |
        docker run -d -p 6969:5000 --name test-container zomato-flask-app:${{ github.sha }}
        sleep 10
        curl -f http://localhost:5000/ || exit 1
        docker stop test-container
        docker rm test-container
    
    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push to DockerHub
      run: |
        docker tag zomato-flask-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/zomato-flask-app:${{ github.sha }}
        docker tag zomato-flask-app:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/zomato-flask-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomato-flask-app:${{ github.sha }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/zomato-flask-app:latest
