name: CI/CD Pipeline

on:
  pull_request:
    branches: [ test, master ]

jobs:
  pr-checks:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create dummy dataset if missing
      run: |
        if [ ! -f "zomato_df.csv" ]; then
          echo "Creating dummy dataset for testing..."
          python -c "
import pandas as pd
import numpy as np

# Create dummy dataset with same structure as original
np.random.seed(42)
n_samples = 1000

data = {
    'online_order': np.random.randint(0, 2, n_samples),
    'book_table': np.random.randint(0, 2, n_samples),
    'rate': np.random.uniform(2.0, 5.0, n_samples),
    'votes': np.random.randint(10, 1000, n_samples),
    'location': np.random.randint(1, 100, n_samples),
    'rest_type': np.random.randint(1, 100, n_samples),
    'cuisines': np.random.randint(1, 200, n_samples),
    'cost': np.random.randint(100, 2000, n_samples),
    'menu_item': np.random.randint(1, 100, n_samples)
}

df = pd.DataFrame(data)
df.to_csv('zomato_df.csv', index=False)
print('Dummy dataset created successfully')
"
        fi
    
    - name: Generate model.pkl for testing
      run: |
        echo "🤖 Generating model.pkl for testing..."
        python model.py
    
    - name: Lint with flake8
      run: |
        echo "🔍 Running flake8 code quality check..."
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Run tests
      run: |
        echo "🧪 Running unit tests..."
        pytest tests/ -v --cov=. --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml