name: Test Branch - Unit Tests

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Generate model.pkl for testing
      run: |
        echo "🤖 Generating model.pkl for testing..."
        python model.py
    
    - name: Run unit tests
      run: |
        echo "🧪 Running unit tests..."
        echo "Current directory: $(pwd)"
        echo "Files in current directory:"
        ls -la
        echo "Files in tests directory:"
        ls -la tests/ || echo "tests directory not found"
        pytest tests/ -v --cov=. --cov-report=html --cov-report=term-missing --tb=short
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: 'Unit Tests'
        path: 'test-results.xml'
        reporter: 'java-junit'